version: "3.4"

services:
  rempersistence:
    image: mongo
    container_name: devices_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=my_user
      - MONGO_INITDB_ROOT_PASSWORD=my_password
    ports:
    - "27020:27017"
    volumes:
      - ./masterdata:/data/db